modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
author="___Evernight___"

[[mods]]
modId="wildhunt"
version="2.0.0"
displayName="Дикая Охота"
description='''
Добавляет трёх боссов из вселенной «Ведьмака»:
- Эредин (Король Дикой Охоты)
- Имлерих (генерал)
- Карантир (магистр)

Боссы имеют уникальные способности, фазы боя и анимации.
Требуется GeckoLib для работы анимаций.
'''

[[dependencies.wildhunt]]
modId="geckolib"
mandatory=true
versionRange="[4.4.5,)"
ordering="NONE"
side="BOTH"